apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  labels:
    category: infra
  finalizers:
    - argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: git@github.com:JaeHeong/my-k8s-gitops.git
    path: infra/cloudflared
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
