{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Release.Name }}-tenant-default
  namespace: istio-system
  labels:
    {{- include "jaehyeong-tech.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      istio: gateway
  configPatches:
    # Run AFTER jwt_authn filter to set default tenant when JWT didn't provide one
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.jwt_authn
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.filters.http.lua.tenant_default
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            defaultSourceCode:
              inlineString: |
                function envoy_on_request(request_handle)
                  -- Always add x-tenant-id header if not present
                  local tenant = request_handle:headers():get("x-tenant-id")
                  if tenant == nil or tenant == "" then
                    request_handle:headers():add("x-tenant-id", "{{ .Values.virtualService.tenantId | default "tenant-default" }}")
                  end
                end
{{- end }}
