# Istio JWT Authentication for Jaehyeong Tech
# - RequestAuthentication: JWT 검증
# - AuthorizationPolicy: 인증 정책
# - EnvoyFilter: JWT 클레임을 헤더로 전달

{{- if .Values.virtualService.enabled }}
---
# RequestAuthentication for Ingress Gateway
# JWT 클레임을 헤더로 변환 (gateway 레벨)
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: {{ .Release.Name }}-gateway-jwt-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: gateway
  jwtRules:
    - issuer: "https://{{ .Values.virtualService.host }}"
      audiences:
        - "{{ .Values.virtualService.host }}"
      jwksUri: "http://{{ .Release.Name }}-auth.{{ .Release.Namespace }}.svc.cluster.local:3001/.well-known/jwks.json"
      forwardOriginalToken: true
      outputClaimToHeaders:
        - header: x-user-id
          claim: userId
        - header: x-user-email
          claim: email
        - header: x-user-role
          claim: role
        - header: x-tenant-id
          claim: tenantId

---
# NOTE: Workload-level RequestAuthentication removed
# Gateway handles all JWT validation and header injection
# Services trust headers from the gateway (x-user-id, x-tenant-id, etc.)
---
# AuthorizationPolicy: Allow all requests, auth handled by gateway + app middleware
# Gateway validates JWT and injects x-user-id, x-tenant-id headers
# Application middleware checks for these headers on protected routes
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-auth-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  action: ALLOW
  rules:
    # Allow all requests - authentication is handled by:
    # 1. Gateway: JWT validation + header injection (x-user-id, x-tenant-id)
    # 2. App middleware: checks x-user-id header for protected routes
    - {}
{{- end }}
