apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "jaehyeong-tech.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "jaehyeong-tech.web.selectorLabels" . | nindent 4 }}
