{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "jaehyeong-tech.labels" . | nindent 4 }}
spec:
  hosts:
    {{- if .Values.virtualService.hosts }}
    {{- range .Values.virtualService.hosts }}
    - {{ . }}
    {{- end }}
    {{- else if .Values.virtualService.host }}
    - {{ .Values.virtualService.host }}
    {{- end }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    # Auth Service (auth, author, users, tenants)
    - match:
        - uri:
            prefix: /api/auth
        - uri:
            prefix: /api/author
        - uri:
            prefix: /api/users
        - uri:
            prefix: /api/tenants
      headers:
        request:
          set:
            x-tenant-id: {{ .Values.virtualService.tenantId | default "default" }}
      route:
        - destination:
            host: {{ .Release.Name }}-auth
            port:
              number: 3001

    # Blog Service (posts, categories, tags)
    - match:
        - uri:
            prefix: /api/posts
        - uri:
            prefix: /api/categories
        - uri:
            prefix: /api/tags
      headers:
        request:
          set:
            x-tenant-id: {{ .Values.virtualService.tenantId | default "default" }}
      route:
        - destination:
            host: {{ .Release.Name }}-blog
            port:
              number: 3002

    # Comment Service
    - match:
        - uri:
            prefix: /api/comments
      headers:
        request:
          set:
            x-tenant-id: {{ .Values.virtualService.tenantId | default "default" }}
      route:
        - destination:
            host: {{ .Release.Name }}-comment
            port:
              number: 3003

    # Page Service
    - match:
        - uri:
            prefix: /api/pages
      headers:
        request:
          set:
            x-tenant-id: {{ .Values.virtualService.tenantId | default "default" }}
      route:
        - destination:
            host: {{ .Release.Name }}-page
            port:
              number: 3004

    # Analytics Service
    - match:
        - uri:
            prefix: /api/analytics
        - uri:
            prefix: /api/visitors
      headers:
        request:
          set:
            x-tenant-id: {{ .Values.virtualService.tenantId | default "default" }}
      route:
        - destination:
            host: {{ .Release.Name }}-analytics
            port:
              number: 3005

    # Storage Service
    - match:
        - uri:
            prefix: /api/files
        - uri:
            prefix: /api/upload
      headers:
        request:
          set:
            x-tenant-id: {{ .Values.virtualService.tenantId | default "default" }}
      route:
        - destination:
            host: {{ .Release.Name }}-storage
            port:
              number: 3006

    # RSS, sitemap, robots - route to blog service
    - match:
        - uri:
            exact: /rss.xml
        - uri:
            exact: /sitemap.xml
        - uri:
            exact: /robots.txt
      headers:
        request:
          set:
            x-tenant-id: {{ .Values.virtualService.tenantId | default "default" }}
      route:
        - destination:
            host: {{ .Release.Name }}-blog
            port:
              number: 3002

    # Default: Web (Frontend)
    - route:
        - destination:
            host: {{ .Release.Name }}-web
            port:
              number: 80
{{- end }}
