apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.jaehyeong.com"
        - "*.jaehyeong.site"
        - "jaehyeong.com"  # 루트 도메인은 별도 추가
