apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaehyeong-tech
  namespace: argocd
  finalizers:
    - argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: git@github.com:JaeHeong/my-k8s-gitops.git
    path: apps/jaehyeong-tech
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jaehyeong-tech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
