apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  labels:
    category: apps
  finalizers:
    - argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: git@github.com:JaeHeong/my-k8s-gitops.git
    path: apps/n8n
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
